.TH "nexusZiaApi::IModuleConfig" 3 "Wed Nov 15 2017" "Nexus ZIA API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nexusZiaApi::IModuleConfig \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBState\fP { \fBUNLOADED\fP = 0, \fBLOAD_START\fP = 1, \fBLOADED\fP = 2, \fBERROR\fP = 3 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (void)=0"
.br
.ti -1c
.RI "virtual void \fBload\fP (void)=0"
.br
.ti -1c
.RI "virtual void \fBreload\fP (void)=0"
.br
.ti -1c
.RI "virtual const \fBState\fP & \fBgetState\fP (void)=0"
.br
.ti -1c
.RI "virtual void \fBsetKey\fP (const std::string &key, const \fBIConfigKey\fP &configKey)=0"
.br
.ti -1c
.RI "virtual const \fBIConfigKey\fP & \fBgetKeyOne\fP (const std::string &key)=0"
.br
.ti -1c
.RI "virtual const std::list< \fBIConfigKey\fP > & \fBgetKey\fP (const std::string &key)=0"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBnexusZiaApi::IModuleConfig::State\fP\fC [strong]\fP"
State of config loading 
.SH "Member Function Documentation"
.PP 
.SS "virtual const std::list<\fBIConfigKey\fP>& nexusZiaApi::IModuleConfig::getKey (const std::string & key)\fC [pure virtual]\fP"
Get list of key in config of module 
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
std::list<IConfigkey> 
.RE
.PP

.SS "virtual const \fBIConfigKey\fP& nexusZiaApi::IModuleConfig::getKeyOne (const std::string & key)\fC [pure virtual]\fP"
Get key unique in config of module 
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
const \fBIConfigKey\fP & 
.RE
.PP

.SS "virtual const \fBState\fP& nexusZiaApi::IModuleConfig::getState (void)\fC [pure virtual]\fP"
Get state of module config In loading, is load, error in config, etc 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "virtual void nexusZiaApi::IModuleConfig::init (void)\fC [pure virtual]\fP"
Init config of module Default value of each key, etc 
.SS "virtual void nexusZiaApi::IModuleConfig::load (void)\fC [pure virtual]\fP"
Load config of module 
.SS "virtual void nexusZiaApi::IModuleConfig::reload (void)\fC [pure virtual]\fP"
Reload config of module 
.SS "virtual void nexusZiaApi::IModuleConfig::setKey (const std::string & key, const \fBIConfigKey\fP & configKey)\fC [pure virtual]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIkey\fP 
.br
\fIconfigKey\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Nexus ZIA API from the source code\&.
