.TH "nexusZiaApi::ILogger" 3 "Wed Nov 15 2017" "Nexus ZIA API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nexusZiaApi::ILogger \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBLevel\fP { \fBDEFAULT\fP = 0, \fBINFO\fP = 1, \fBSUCCESS\fP = 2, \fBWARNING\fP = 3, \fBERROR\fP = 4, \fBFATAL_ERROR\fP = 5 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBlog\fP (const ILogger::Level &level, const std::string &msg)=0"
.br
.ti -1c
.RI "virtual void \fBlogDefault\fP (const std::string &msg)=0"
.br
.ti -1c
.RI "virtual void \fBlogInfo\fP (const std::string &msg)=0"
.br
.ti -1c
.RI "virtual void \fBlogSuccess\fP (const std::string &msg)=0"
.br
.ti -1c
.RI "virtual void \fBlogWarning\fP (const std::string &msg)=0"
.br
.ti -1c
.RI "virtual void \fBlogError\fP (const std::string &msg)=0"
.br
.ti -1c
.RI "virtual void \fBlogFatalError\fP (const std::string &msg)=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void nexusZiaApi::ILogger::log (const ILogger::Level & level, const std::string & msg)\fC [pure virtual]\fP"
Log message 
.PP
\fBParameters:\fP
.RS 4
\fIlevel\fP Type of log 
.br
\fImsg\fP Message 
.RE
.PP

.SS "virtual void nexusZiaApi::ILogger::logDefault (const std::string & msg)\fC [pure virtual]\fP"
Log default message 
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP 
.RE
.PP

.SS "virtual void nexusZiaApi::ILogger::logError (const std::string & msg)\fC [pure virtual]\fP"
Log error message 
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP 
.RE
.PP

.SS "virtual void nexusZiaApi::ILogger::logFatalError (const std::string & msg)\fC [pure virtual]\fP"
Log fatal error message 
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP 
.RE
.PP

.SS "virtual void nexusZiaApi::ILogger::logInfo (const std::string & msg)\fC [pure virtual]\fP"
Log info message 
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP 
.RE
.PP

.SS "virtual void nexusZiaApi::ILogger::logSuccess (const std::string & msg)\fC [pure virtual]\fP"
Log success message 
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP 
.RE
.PP

.SS "virtual void nexusZiaApi::ILogger::logWarning (const std::string & msg)\fC [pure virtual]\fP"
Log warning message 
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Nexus ZIA API from the source code\&.
