.TH "nexusZiaApi::IConfigKey" 3 "Wed Nov 15 2017" "Nexus ZIA API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nexusZiaApi::IConfigKey \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBVALUE\fP = 0, \fBSCOPE\fP = 1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetType\fP (const Type &type)=0"
.br
.ti -1c
.RI "virtual const Type & \fBgetType\fP (void) const =0"
.br
.ti -1c
.RI "virtual void \fBsetName\fP (const std::string &name)=0"
.br
.ti -1c
.RI "virtual const std::string & \fBgetName\fP (void) const =0"
.br
.ti -1c
.RI "virtual void \fBsetValue\fP (const std::string &value)=0"
.br
.ti -1c
.RI "virtual const std::string & \fBgetValue\fP (void) const =0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual const std::string& nexusZiaApi::IConfigKey::getName (void) const\fC [pure virtual]\fP"
Get name of config key 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "virtual const Type& nexusZiaApi::IConfigKey::getType (void) const\fC [pure virtual]\fP"
Get type of config key 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "virtual const std::string& nexusZiaApi::IConfigKey::getValue (void) const\fC [pure virtual]\fP"
Get value of config key 
.PP
\fBAttention:\fP
.RS 4
Return '' for scope 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "virtual void nexusZiaApi::IConfigKey::setName (const std::string & name)\fC [pure virtual]\fP"
Set name of config key 
.PP
\fBParameters:\fP
.RS 4
\fItype\fP 
.RE
.PP

.SS "virtual void nexusZiaApi::IConfigKey::setType (const Type & type)\fC [pure virtual]\fP"
Set type of config key 
.PP
\fBParameters:\fP
.RS 4
\fItype\fP 
.RE
.PP

.SS "virtual void nexusZiaApi::IConfigKey::setValue (const std::string & value)\fC [pure virtual]\fP"
Set value of config key 
.PP
\fBAttention:\fP
.RS 4
Not for scope type 
.RE
.PP
\fBParameters:\fP
.RS 4
\fItype\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Nexus ZIA API from the source code\&.
