.TH "nexusZiaApi::IModuleCore" 3 "Wed Nov 15 2017" "Nexus ZIA API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nexusZiaApi::IModuleCore \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBState\fP { \fBOFF\fP = 0, \fBUP\fP = 1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBstart\fP (void)=0"
.br
.ti -1c
.RI "virtual void \fBstop\fP (void)=0"
.br
.ti -1c
.RI "virtual void \fBreload\fP (void)=0"
.br
.ti -1c
.RI "virtual void \fBsetName\fP (const std::string &name)=0"
.br
.ti -1c
.RI "virtual const \fBIModuleConfig\fP & \fBgetModuleConfig\fP (void)=0"
.br
.ti -1c
.RI "virtual void \fBhooksCall\fP (const \fBIHooks::Types\fP &hooksType, \fBIHttpData\fP &data)=0"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBnexusZiaApi::IModuleCore::State\fP\fC [strong]\fP"
State of module loading 0: OFF / 1: UP 
.SH "Member Function Documentation"
.PP 
.SS "virtual const \fBIModuleConfig\fP& nexusZiaApi::IModuleCore::getModuleConfig (void)\fC [pure virtual]\fP"
Get module config 
.PP
\fBReturns:\fP
.RS 4
const \fBIModuleConfig\fP 
.RE
.PP

.SS "virtual void nexusZiaApi::IModuleCore::hooksCall (const \fBIHooks::Types\fP & hooksType, \fBIHttpData\fP & data)\fC [pure virtual]\fP"
Function call if event in the hook subsribe 
.PP
\fBParameters:\fP
.RS 4
\fIhooksType\fP Type of hook 
.br
\fIdata\fP Data http 
.RE
.PP

.SS "virtual void nexusZiaApi::IModuleCore::reload (void)\fC [pure virtual]\fP"
Reload module
.PP
Module is not stop and restart, module is always UP 
.SS "virtual void nexusZiaApi::IModuleCore::setName (const std::string & name)\fC [pure virtual]\fP"
Set name of module 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of module 
.RE
.PP

.SS "virtual void nexusZiaApi::IModuleCore::start (void)\fC [pure virtual]\fP"
Start module 
.SS "virtual void nexusZiaApi::IModuleCore::stop (void)\fC [pure virtual]\fP"
Stop module 

.SH "Author"
.PP 
Generated automatically by Doxygen for Nexus ZIA API from the source code\&.
