.TH "nexusZiaApi::IHttpHeader" 3 "Wed Nov 15 2017" "Nexus ZIA API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nexusZiaApi::IHttpHeader \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetKey\fP (const std::string &key, const std::string &value)=0"
.br
.ti -1c
.RI "virtual const std::string & \fBgetKey\fP (const std::string &key)=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual const std::string& nexusZiaApi::IHttpHeader::getKey (const std::string & key)\fC [pure virtual]\fP"
Get key of header HTTP 
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "virtual void nexusZiaApi::IHttpHeader::setKey (const std::string & key, const std::string & value)\fC [pure virtual]\fP"
Set key of header HTTP 
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP 
.br
\fIvalue\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Nexus ZIA API from the source code\&.
