.TH "nexusZiaApi::IAPIServer" 3 "Wed Nov 15 2017" "Nexus ZIA API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nexusZiaApi::IAPIServer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBIHooks\fP & \fBgetHooks\fP (void)=0"
.br
.ti -1c
.RI "virtual const \fBIHooks\fP & \fBgetHooks\fP (void) const =0"
.br
.ti -1c
.RI "virtual \fBILogger\fP & \fBgetLogger\fP (void)=0"
.br
.ti -1c
.RI "virtual const \fBILogger\fP & \fBgetLogger\fP (void) const =0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBIHooks\fP& nexusZiaApi::IAPIServer::getHooks (void)\fC [pure virtual]\fP"
Get hooks API server 
.PP
\fBAttention:\fP
.RS 4
This functions allow edit of reference 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "virtual const \fBIHooks\fP& nexusZiaApi::IAPIServer::getHooks (void) const\fC [pure virtual]\fP"
Get hooks API server 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "virtual \fBILogger\fP& nexusZiaApi::IAPIServer::getLogger (void)\fC [pure virtual]\fP"
Get logger API server 
.PP
\fBAttention:\fP
.RS 4
This functions allow edit of reference 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "virtual const \fBILogger\fP& nexusZiaApi::IAPIServer::getLogger (void) const\fC [pure virtual]\fP"
Get logger API server 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Nexus ZIA API from the source code\&.
