.TH "nexusZiaApi::IHttpData" 3 "Wed Nov 15 2017" "Nexus ZIA API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nexusZiaApi::IHttpData \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetHeader\fP (const \fBIHttpHeader\fP &header) const "
.br
.ti -1c
.RI "virtual \fBIHttpHeader\fP & \fBgetHeader\fP (void)"
.br
.ti -1c
.RI "virtual const \fBIHttpHeader\fP & \fBgetHeader\fP (void) const "
.br
.ti -1c
.RI "virtual void \fBsetBody\fP (const std::string &data)=0"
.br
.ti -1c
.RI "virtual const std::string & \fBgetBody\fP (void) const =0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual const std::string& nexusZiaApi::IHttpData::getBody (void) const\fC [pure virtual]\fP"
Get body of HTTP Data 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "virtual \fBIHttpHeader\fP& nexusZiaApi::IHttpData::getHeader (void)\fC [virtual]\fP"
Get HTTP Header 
.PP
\fBAttention:\fP
.RS 4
This functions allow edit of reference 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "virtual const \fBIHttpHeader\fP& nexusZiaApi::IHttpData::getHeader (void) const\fC [virtual]\fP"
Get HTTP Header 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "virtual void nexusZiaApi::IHttpData::setBody (const std::string & data)\fC [pure virtual]\fP"
Set the body of HTTP Data 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP 
.RE
.PP

.SS "virtual void nexusZiaApi::IHttpData::setHeader (const \fBIHttpHeader\fP & header) const\fC [virtual]\fP"
\fBDefine\fP header of HTTP data (or message) 
.PP
\fBParameters:\fP
.RS 4
\fIheader\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Nexus ZIA API from the source code\&.
